#!/usr/bin/env bash
# Verify security and privacy invariants in the BUILT artifact (public/), not the config.
# Exists because every security bug this project has had built successfully: the config
# said one thing and the emitted site said another. Run after `zola build`; CI runs it
# before deploy and fails the pipeline on drift.
#
# Scope note: these checks run over EVERY generated page. tabi resolves several settings
# per page, so a single page can carry a weaker policy than the homepage. Checking only
# index.html cannot see that.
set -euo pipefail
cd "$(dirname "$0")/.."
fail() { echo "FAIL: $1" >&2; exit 1; }

[ -f public/index.html ] || fail "public/index.html missing — build first"

pages=$(find public -name '*.html' -type f | sort)
[ -n "$pages" ] || fail "no HTML pages found in public/"
echo "checking $(printf '%s\n' "$pages" | wc -l) pages"

# 1. Content-Security-Policy: present on every page, and never weaker than intended.
#    Asserted as properties rather than one exact string: tabi appends 'self' to some
#    directives situationally (e.g. font-src on KaTeX pages), which is harmless, while
#    'unsafe-inline' and wildcard hosts are not.
for f in $pages; do
    # Zola emits a meta-refresh stub for .../page/1/. It carries no content, no script
    # and no CSP by design; the page it redirects to is checked like any other.
    if grep -q 'http-equiv=refresh' "$f" && grep -q '<title>Redirect</title>' "$f"; then
        continue
    fi
    csp=$(grep -o "default-src[^\"]*" "$f" | head -1 || true)
    [ -n "$csp" ] || fail "no CSP emitted on ${f#public/}"
    case "$csp" in *"https://*"*) fail "wildcard host (https://*) in CSP on ${f#public/} — the extra.hcard ordering bug is back";; esac
    # 'unsafe-inline' would be silently added by enabling mermaid or a comment backend
    # on a single page. Measured 2026-08-28: mermaid = true relaxes style-src page-wide.
    case "$csp" in *unsafe-inline*) fail "unsafe-inline in CSP on ${f#public/} — a page-level feature (mermaid? comments?) relaxed the policy";; esac
    case "$csp" in *unsafe-eval*) fail "unsafe-eval in CSP on ${f#public/}";; esac
    case "$csp" in *"img-src 'self' data:"*) ;; *) fail "img-src is not 'self' data: on ${f#public/}";; esac
    case "$csp" in *"style-src 'self'"*) ;; *) fail "style-src does not start at 'self' on ${f#public/}";; esac
done
echo "CSP (homepage): $(grep -o "default-src[^\"]*" public/index.html | head -1)"

# 2. Class-based highlighting: zero inline style ATTRIBUTES anywhere.
# Match style= only inside a tag (after < and before >), so prose or code spans that
# merely mention the string do not trip the gate.
if grep -rlqE '<[a-zA-Z][^>]*[[:space:]]style=' $pages 2>/dev/null; then
  echo "offending pages:" >&2
  grep -rlE '<[a-zA-Z][^>]*[[:space:]]style=' $pages >&2 || true
  fail "inline style= attribute in a page — highlighting fell back to inline mode, or a shortcode emitted one"
fi

# 3. No off-site subresources. The CSP would block these at runtime, which means the
#    feature silently does nothing rather than failing loudly. The known trap is the
#    theme's serve_local_mermaid default flipping to a jsDelivr CDN URL on a bump.
#    Cloudflare's analytics beacon is the one permitted exception (see config.toml).
# Anchors in prose legitimately point off-site, so only subresource-bearing tags are
# examined: script, link, img, iframe.
offsite=$(grep -rhoE '<(script|link|img|iframe)[^>]*>' $pages \
    | grep -oE '(src|href)="?https?://[^" >]*' \
    | grep -vE '="?https?://(linuxgroot\.net|static\.cloudflareinsights\.com)' \
    | sort -u || true)
if [ -n "$offsite" ]; then
  printf '%s\n' "$offsite" >&2
  fail "off-site subresource in built output — the CSP would block it at runtime and the feature would fail silently"
fi

# 4. Every blog page carries an Open Graph image. Without one, a link posted anywhere
#    renders as bare text, which is a silent failure: the page is fine, the build is
#    green, and only the reach is gone. Cards are generated by
#    scripts/render-social-cards.py, which also writes the front-matter key; this check
#    catches a post added without running it.
# Checking merely that og:image EXISTS is not enough, and a positive control proved it:
# tabi resolves social_media_card page > section > config, so a post that lost its own
# card silently inherits the blog section's generic one. The build stays green and every
# post shares one indistinguishable preview. So the card must match the page it is on.
#
# Written as an explicit if rather than `grep -q ... && continue`: under set -e that
# idiom's exit status depends on which command in the && list failed, which is the
# footgun that produced a false PASS elsewhere in this project.
for f in $(find public/blog -name '*.html' -type f 2>/dev/null | sort); do
    if grep -q 'http-equiv=refresh' "$f"; then
        continue
    fi
    got=$(grep -oE 'social_cards/[A-Za-z0-9._-]+\.png' "$f" | head -1 || true)
    [ -n "$got" ] || fail "no og:image on ${f#public/} — run scripts/render-social-cards.py"
    # public/blog/scheduler/what-your-job-costs/index.html -> blog-scheduler-what-your-job-costs.png
    want=$(printf '%s' "${f#public/}" | sed 's|/index\.html$||; s|\.html$||; s|/|-|g')
    [ "$got" = "social_cards/${want}.png" ] \
        || fail "${f#public/} shows card '${got##*/}', expected '${want}.png' — it is inheriting another page's card; run scripts/render-social-cards.py"
done

# 5. HTTP-header policies shipped for Workers to serve.
[ -f public/_headers ] || fail "public/_headers missing"
grep -q 'X-Frame-Options: DENY' public/_headers || fail "_headers lost X-Frame-Options"
grep -q 'X-Content-Type-Options: nosniff' public/_headers || fail "_headers lost nosniff"

# 6. Privacy: the built site must not contain identifying or work-related strings.
#
# The patterns themselves are deliberately NOT in this file. This repo is public, so a
# literal deny-list here would publish exactly the strings it exists to suppress — which
# is what this script did until 2026-08-28. Patterns come from outside the repo:
#   local: ~/.config/linuxgroot/leak-patterns   (one POSIX basic regex per line)
#   CI:    $LEAK_PATTERNS_FILE, written from a GitHub Actions secret
# Only file names and match counts are ever printed, never a matched line.
patterns="${LEAK_PATTERNS_FILE:-$HOME/.config/linuxgroot/leak-patterns}"
if [ -f "$patterns" ] && [ -s "$patterns" ]; then
    hits=$(grep -rlif "$patterns" public/ | grep -v '^public/search_index' || true)
    if [ -n "$hits" ]; then
        echo "files containing a forbidden pattern:" >&2
        printf '%s\n' "$hits" >&2
        fail "identity- or work-bearing string in built output ($(printf '%s\n' "$hits" | wc -l) file(s))"
    fi
    echo "leak scan: clean against $(grep -cve '^[[:space:]]*$' "$patterns") pattern(s)"
elif [ "${CI:-}" = "true" ]; then
    fail "leak-pattern file missing in CI — set the LEAK_PATTERNS secret or unset this gate deliberately"
else
    echo "WARNING: no leak-pattern file at $patterns — privacy scan SKIPPED" >&2
fi

echo "OK: all build invariants hold"
